### ISSUE TITLE
New User Sign Up Error

### ISSUE THREAD

**Issue by damathews** [megawina/deliver.me#3]
Hi,

I have looked through various files to see what would be causing this, but I am getting an error when trying to sign up as a "new user" saying that the password is unacceptable.

I cannot find anywhere that explains a required password format. Do you have any advice for what would be causing this?

Thank you for your help!

**Comment by megawina** [comment]
@damathews of course. you have to open AISignUpViewController.m and find there method 
- (IBAction)actionSignUp:(id)sender 

There is some kind of info validation. For example, phone has to be in "+11(111)111-1111" format. And so on. Thanks.

**Comment by damathews** [comment]
Thank you but the error I am seeing has to do with the password needing 4 symbols but I cannot find anywhere inside the project what it is actually validating. Thank you for your help.
![img_1225](https://cloud.githubusercontent.com/assets/17294944/15002907/3d01bcec-1174-11e6-908d-f9481154a17d.PNG)

**Comment by damathews** [comment]
I found the part in the code referencing the phone number so thank you!
Now I am getting an ongoing spinning icon that never finishes loading. Do you have any advice for what would be causing this?
![img_1227](https://cloud.githubusercontent.com/assets/17294944/15016927/62db466e-11e1-11e6-8805-827bce9da0f1.jpg)

**Comment by megawina** [comment]
@damathews you have to debug code and find issue.
