### ISSUE TITLE
Change to New Order Screen

### ISSUE THREAD

**Issue by hgrieder** [megawina/deliver.me#4]
Good morning - 

Could you provide an update to the New Order screen? I see entries for Your Address, Recipient Address, Recipient Phone, & Order Date/Time but instead of Recipient Address & Recipient Phone I would like to add an Order Description box if possible so that the courier knows what the requester wants. 

Thanks, 

Hayden

**Comment by megawina** [comment]
Hi, @hgrieder . It`s easy work, so I think that it could be better if you`ll provide that :)
